# fly.toml app configuration file generated for aged-cherry-5244 on 2023-07-17T19:39:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-cherry-5244"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
